### ISSUE TITLE
Search с подсветкой

### ISSUE THREAD

**Issue by yuristsepaniuk** [YauheniyaBasaranovich/NewsPortal#7]
Ну и таск выдали!!! Делай как получится, но плиз разберись, что это такое:
https://www.elastic.co/guide/en/elasticsearch/guide/current/_closer_is_better.html

Есть термин slop, он отвечает как далеко друг от друга термины поиска. Если они ближе друг к другу, то эта новость должна быть выше в поиске.

Крутой таск, посмотрим что ты сделаешь! Fun fun fun!

Thx
-Yura

**Comment by YauheniyaBasaranovich** [comment]
У меня получилось вот так) Интересно твое мнение.

![photo_2017-05-01_13-12-56](https://cloud.githubusercontent.com/assets/22647154/25577704/1888cfd4-2e71-11e7-8a22-cfd69722f392.jpg)

**Comment by yuristsepaniuk** [comment]
Задача выполнена, полистал код :) Но есть вариант лучше :( Повторю, реализация есть у тебя, но на больших данных она не сработает :( Я сейчас тут напишу идею, плиз расшарь ее с остальными бойцами своей группы.

1. когда мы выполняем поиск по нескольким словам, то правильно, ты его разбиваешь на термины terms: a) двадцать b) человек. Это касательно твоего запроса. Обрати внимание, кто определяет какой из терминов более весомый a) или b)? Ответ никакой. Найти доки, со словами двадцать, но без слова человек, или наоборот. Гугл имеет спец синтаксис, которым ты можешь ему задавать приоритеты терминов прямо в строке запроса. В конкретном случае, мы можем проигнорить вес терминов запроса, мы студенты. Поэтому можно взять первый термин за главный, второй за второстепенный, второстепенный отталкивается слопом от первого. Cool!
2. Когда мы приехали на сервер с таким запросом, можем ли мы прокатиться по всем документам с таким запросом? Реально дорого это :( Очевидно нужен индекс. Т.е. каждая новая статейка, когда попадает в базу, дробится на термины, в которых указано какой позишен этого термина в исходном доке.
Пример:
2.1. создаем статью "Юра С не смотрел звездные войны и это правда!". 
2.2. разбиваем на термины "Юра", "С", "не", "смотрел", "звездные", "войны", "и", "это", "правда". Тут куча проблем: потому что желательно убрать стоп термины, такие как "и", но не такие как "С" или "не", а еще лучше "не" включить в термин "смотрел" --> "не смотрел". Так мысли вслух.
2.3. создаем индекс пишу на псевдо формате с отступами, так удобно
--"Юра":
----"articleIds": ["someId1", "someId2"]
----"slops":
------"someId1":
--------offset: 0 (так как в доке someId1 Юра не имеет отступ, он вначале дока)
------"someId2":
--------offset: 100 (так как в доке someId2 Юра реально далеко)
2.4. значит ты будешь бежать по индексу и уже наблюдать за офсетами, а не считать их. Минимум ты сжимаешь текст, многие архиваторы так работают, плюс ты бежишь по сжатому тексту, в котором уже все подсчеты по слопам сделаны.
2.5. твой сервер должен быть настроен так, что он игнорит поиск терминов, между которыми слоп больше сконфигурированного. Иначе если искать полное включение, то мы не закончим даже с индексированными данными.
2.6. вообще я написал не оптимальный индекс по слопам, так как идеальнее получать данные по ключу "term" + "slop". Это похоже на плотное дерево, о котором мы говорили в момент фильтра по датам.

Note: эту задачу похожим образом решает elasticsearch. Важно хотя бы понимать причины, почему это дорого!

-Юра
